version: 2.1
jobs:
  hygiene_tests:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hygiene tests
          command: bash -xeo pipefail .hygiene/run_hygiene.sh
      - store_artifacts:
          path: .hygiene/output
      - store_test_results:
          path: .hygiene/output
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - hygiene_tests
